/* One weekly desk surface; source explorers remain available underneath. */
const jump=(id,label)=>`<button class="text-link" onclick="show('${id}')">${label} ↗</button>`;
const signed=x=>x>0?'up':x<0?'dn':'';
const compactName=s=>String(s).replace(/^[^/]+\//,'').replace(/-/g,' ');
function sourceStamp(id){const f=T.freshness(D,id);return `<span class="source-stamp ${f.state.toLowerCase()}">${esc(D.sources[id].name)} · ${esc(f.date||'unavailable')} · ${f.state}</span>`}
function plotSafe(id,tr,layout){if(typeof Plotly==='undefined'){document.getElementById(id).innerHTML=empty('Chart library unavailable','The tables and readings remain available. Reconnect to load charts.');return}Plotly.react(id,tr,lay(layout),CFG)}
const sectionGuides={
 demand:'Weekly tokens processed through OpenRouter. Compare this week’s growth with the prior week to see whether growth is speeding up or slowing down.',
 weights:'Open-weight models make their trained parameters available. Closed-weight models do not. Unknown includes usage that cannot be classified.',
 capture:'Each cell shows the latest level, followed by its change. Compare a lab across sources; the columns cover different customer groups.',
 movers:'The largest gains and losses in OpenRouter token share. Both are included; click a column heading to sort.',
 launches:'Recently listed models with observed usage. Compare the model’s share change with its parent lab’s change over the same period.',
 cost:'Compare benchmark capability with published token prices. Higher scores mean stronger benchmark performance; lower prices mean cheaper tokens.',
 context:'Business adoption and consumer popularity provide a second perspective on AI demand. Neither measures token volume.',
 coverage:'Check how recent each dataset is, what it covers, and where it can give a biased picture.'
};
function miniBlock(id,title,body,note='',extra=''){return `<section class="block desk-block" id="${id}"><div class="bh"><span class="section-no">${({demand:'01',capture:'02',weights:'03',movers:'04',launches:'05',cost:'06',context:'07',coverage:'08'})[id]||''}</span><h2>${title}</h2><span class="sp"></span>${extra}</div>${sectionGuides[id]?`<p class="section-guide">${sectionGuides[id]}</p>`:''}${body}${note?`<div class="note">${note}</div>`:''}</section>`}

let deskLag=1,deskLab='',deskQuery='',deskGroup='model',deskAllLabs=false;
BUILD.overview=function(el){
 const lag=deskLag,o=T.orSummary(D.openrouter,lag),b=T.board(D,lag),p=D.pricing;
 const leaders=b.rows.filter(r=>T.finite(r.or.delta)).sort((a,b)=>b.or.delta-a.or.delta),gainer=leaders[0];
 const priced=(p.rows||[]).filter(r=>T.finite(r.idx)).sort((a,b)=>b.idx-a.idx||a.pout-b.pout),top=priced[0];
 const risk=D.sourceOrder.filter(id=>['Missing','Stale'].includes(T.freshness(D,id).state));
 const divergences=b.rows.filter(r=>T.finite(r.or.delta)&&T.finite(r.tokens.delta)&&r.or.delta*r.tokens.delta<0).sort((a,b)=>Math.abs(b.or.delta-b.tokens.delta)-Math.abs(a.or.delta-a.tokens.delta));
 const diverge=divergences[0];
 const growth=o?.wow;const motion=o?.acceleration==null?'Need three consecutive weeks':Math.abs(o.acceleration)<0.0005?'Weekly growth rate unchanged':o.acceleration>0?'Weekly growth accelerating':'Weekly growth decelerating';
 const kpi=(label,value,sub,foot,cls='')=>`<div class="read"><div class="l">${label}</div><div class="v ${cls}">${value}</div><div class="s">${sub}</div><div class="kpi-foot">${foot}</div></div>`;
 el.innerHTML=`<div class="desk-head"><div><div class="eyebrow">INFERENCE MARKETS / WEEKLY MONITOR</div><h1>Token desk<span class="edition">${o?'WEEK ENDED '+o.end:'LATEST AVAILABLE'}</span></h1></div><div class="desk-controls"><span class="lbl">Compare with</span>${seg('desk-lag',[['1','1 week ago'],['4','4 weeks ago'],['13','13 weeks ago']],String(lag))}<button class="print-button" id="print-desk" title="Print or save the weekly dashboard as PDF">Print / PDF</button></div></div>
 <div class="scope-strip"><span class="scope-dot"></span><b>Observed AI usage, by source.</b><span>Each source measures part of the market. Global token demand is not measured here.</span><button class="text-link" onclick="document.getElementById('coverage').scrollIntoView({behavior:'smooth'})">${risk.length?risk.length+' coverage gaps':'Source coverage'} ↓</button></div>
 <details class="reading-guide"><summary>How to read this dashboard: tokens, shares, prices and missing data</summary><div class="guide-grid">
 <p><b>Tokens measure usage.</b> A token is a piece of text a model reads or produces. M = million, B = billion, T = trillion, Q = quadrillion. Token counts are not revenue or computing capacity.</p>
 <p><b>% and pp mean different things.</b> A share rising from 10% to 12% gains 2 percentage points (pp). Volume rising from 100 to 120 grows 20%.</p>
 <p><b>Comparison periods.</b> The buttons compare the latest week with 1, 4 or 13 weeks earlier. The volume card always compares consecutive weeks. Ramp adoption always compares months.</p>
 <p><b>Input vs. output prices.</b> Input is text sent to a model; output is text it generates. Prices are dollars per million tokens. Cached input reuses previously processed text.</p>
 <p><b>Capability vs. openness.</b> Artificial Analysis (AA) scores measure benchmark performance, not popularity. Open weights means the model parameters are available; it does not automatically mean free usage.</p>
 <p><b>Missing data and colors.</b> — means unavailable, not zero. Green and red show increases and decreases, not buy/sell signals. For popularity ranks, a smaller number is better.</p>
 </div></details>
 <div class="reads desk-reads">
 ${kpi('OpenRouter · weekly tokens',fT(o?.now),`<strong class="${signed(growth)}">${fS(growth)} vs prior week</strong> · ${motion}`,o?`${o.date} → ${o.end} · complete week`:'No complete observed week')}
 ${kpi('Largest lab share gain',gainer?esc(gainer.lab):'—',gainer?`<strong class="${signed(gainer.or.delta)}">${fPP(gainer.or.delta)}</strong> · ${fP(gainer.or.value)} of OpenRouter tokens`:'Comparison unavailable',`vs ${lag} week${lag>1?'s':''} earlier · source-specific`)}
 ${kpi('OpenRouter · open-weight share',fP(o?.open),`${fPP(o?.openDelta)} vs ${lag} week${lag>1?'s':''} earlier`,`${fP(o?.unknown)} unclassified · share of all OpenRouter tokens`)}
 ${kpi('Top benchmarked model · price',top?`<span class="u">In</span> ${f$(top.pin)} <span class="u">Out</span> ${f$(top.pout)}`:'—',top?esc(compactName(top.model)):'No benchmark-matched prices',`Input / output · dollars per million tokens · ${p.asof||'unavailable'}`)}
 </div>
 <div class="weekly-read"><span class="eyebrow">THIS WEEK’S READ</span><p>${o&&o.wow!=null?`OpenRouter volume ${o.wow>=0?'grew':'fell'} <b>${fP(Math.abs(o.wow))}</b>${o.prior!=null?`, versus ${fS(o.prior)} the prior week`:''}. `:'OpenRouter volume comparison is unavailable. '}${diverge?`<b>${esc(diverge.lab)}</b> moved ${fPP(diverge.or.delta)} in OpenRouter token share and ${fPP(diverge.tokens.delta)} on Vercel over ${lag}W; the usage signals diverge. `:''}${p.n_snapshots===1?'A price-decline rate needs another price observation.':''}</p></div>
 <div class="desk-grid">
 ${miniBlock('demand' ,'Is observed demand accelerating?',`<div class="inline-stats"><span>This week’s growth <b class="${signed(growth)}">${fS(growth)}</b></span><span>Prior week’s growth <b>${fS(o?.prior)}</b></span><span>Growth-rate change <b class="${signed(o?.acceleration)}">${fPP(o?.acceleration)}</b></span></div><div id="desk-volume" class="plot compact"></div>`,`${sourceStamp('openrouter')}<br>Growth is for this marketplace. Free routing, model mix and different tokenizers can move token counts.`,jump('openrouter','Explore'))}
 ${miniBlock('weights','Open vs. closed model usage',`<div id="desk-weights" class="plot compact"></div><div class="inline-stats"><span>Open <b>${fP(o?.open)}</b></span><span>Closed <b>${fP(o?.closed)}</b></span><span>Unknown <b>${fP(o?.unknown)}</b></span><span>Free model variants <b>${fP(o?.free)}</b></span></div>`,`Share of all OpenRouter tokens, including the unnamed bucket. Free is a separate, overlapping cut. Weights follow catalog metadata; “frontier” is a quality distinction, not a license.`)}
 </div>
 ${miniBlock('capture','Lab share across sources',`<div class="capture-tools"><label>Lab <input class="q" id="desk-lab" placeholder="Filter labs…" value="${esc(deskLab)}"></label><span>Latest level <b>/ change vs comparison period</b> · pp = percentage points</span><span class="key up">↑ gaining</span><span class="key dn">↓ losing</span></div><div id="desk-board"></div><div class="board-toggle"><button class="text-link" id="desk-all-labs"></button></div>`,`Compare directions across independent populations. Vercel tokens, spend and requests share the same gateway; they are not three independent confirmations. Ramp stays monthly. Rank changes are places, not share.`,jump('method','Definitions'))}
 <div class="desk-grid wide-left">
 ${miniBlock('movers','Biggest token-share gains and losses',`<div class="capture-tools">${seg('desk-group',[['model','Models'],['lab','Labs']],deskGroup)}<label class="sr-only" for="desk-query">Filter models or labs</label><input class="q" id="desk-query" placeholder="Find model or lab…" value="${esc(deskQuery)}"><span>Largest share changes · vs ${lag} week${lag>1?'s':''} ago</span></div><div id="desk-movers"></div>`,`Named OpenRouter rows only; absent top-50 models may retain usage in “other”. Missing comparison weeks stay blank.`,jump('openrouter','All usage'))}
 ${miniBlock('launches','Recent models: usage and lab share',`<div id="desk-launches"></div>`,`Listed date is OpenRouter catalog creation, not a verified launch date. Model and parent-lab share changes are descriptive; they do not establish release causality.`)}
 </div>
 <div class="desk-grid wide-left">
 ${miniBlock('cost','Model capability vs. token price',`<div class="capture-tools"><span>Artificial Analysis benchmark score × published price</span>${seg('desk-price',[['pin','Input price'],['pout','Output price']],'pout')}</div><div id="desk-frontier" class="plot compact"></div><div id="desk-cost-table"></div>`,`${sourceStamp('pricing')}<br>${p.n_snapshots>1?'Same-model input/output price changes available in the price explorer.':'Only one pricing snapshot: the rate of price decline is not yet measurable.'} No assumed cache ratio or blended cost.`,jump('pricing','Price history'))}
 ${miniBlock('context','Business adoption & consumer popularity',`<div id="desk-context"></div>`,`Adoption, DNS rank and company disclosures measure different things. They are context for demand, not additional token counts.`)}
 </div>
 <div class="desk-readthrough"><span class="section-no">WHAT THIS MEANS</span><div><b>Model labs</b><p>Read token share beside spend share. A usage gain is not automatically a revenue gain.</p></div><div><b>Hyperscalers</b><p>These sources do not expose serving location. Lab share cannot identify the cloud capturing it.</p></div><div><b>Compute</b><p>Token growth is a demand clue. Model size, caching, batching and efficiency prevent a direct GPU-revenue conversion.</p></div></div>
 ${miniBlock('coverage','Source coverage & reporting dates',`<div id="desk-coverage"></div>`,`Build date ${D.built} is not the observation date. Weekly refresh; the last available observations remain visible when a pull fails.`)}
 <div class="desk-footer">TOKEN DESK <span>OpenRouter & Vercel data: CC BY 4.0 · Artificial Analysis · Cloudflare Radar · Ramp AI Index</span>${jump('method','Methodology & run log')}</div>`;
 bindSeg('desk-lag',v=>{deskLag=+v;BUILD.overview(el)});document.getElementById('print-desk').onclick=()=>window.print();
 function boardTable(){const columns=[['or','OpenRouter','Token share · weekly',b.orDate,b.orPrev],['tokens','Vercel','Token share · 7-day average',b.vercelDate,b.vercelPrev],['spend','Vercel','Spend share · 7-day average',b.vercelDate,b.vercelPrev],['ramp','Ramp','Paid adoption · monthly',b.rampDate,b.rampPrev],['cf','Cloudflare','Popularity rank · lower is better',b.cfDate,b.cfPrev]];
  const cell=(c,rank)=>{let value=rank?(c.value==null?'—':'#'+c.value):fP(c.value),delta=rank?(c.delta==null?'—':c.delta===0?'0':`${c.delta<0?'↑':'↓'}${Math.abs(c.delta)}`):fPP(c.delta);return `<td class="n"><span class="cell-level">${value}</span><strong class="${signed(rank?-c.delta:c.delta)}">${delta}</strong></td>`};
  const matching=b.rows.filter(r=>r.lab.toLowerCase().includes(deskLab.toLowerCase()));const rows=deskAllLabs||deskLab?matching:matching.slice(0,12);document.getElementById('desk-all-labs').textContent=deskAllLabs?'Show leading 12 labs':`Show all ${matching.length} labs`;document.getElementById('desk-all-labs').onclick=()=>{deskAllLabs=!deskAllLabs;boardTable()};
  document.getElementById('desk-board').innerHTML=`<div class="tw"><table class="capture-table"><thead><tr><th>Model developer / lab</th>${columns.map(([k,name,unit,date,prev])=>`<th class="n">${name}<small>${unit}</small><small>${k==='or'||k==='tokens'||k==='spend'?'Week of ':''}${date||'unavailable'}<br>vs ${prev||'unavailable'}</small></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td class="k">${labChip(r.lab)}</td>${columns.map(([k])=>cell(r[k],k==='cf')).join('')}</tr>`).join('')||'<tr><td colspan="6">No matching labs</td></tr>'}</tbody></table></div>`}
 document.getElementById('desk-lab').oninput=e=>{deskLab=e.target.value;boardTable()};boardTable();
 if(o){const x=D.openrouter.weeks,tot=D.openrouter.total;plotSafe('desk-volume',[{x,y:tot,type:'bar',marker:{color:'#8abfb0'},hovertemplate:'%{x}<br>%{y:.3s} tokens<extra>OpenRouter</extra>'}],{yaxis:{tickformat:'.2s',rangemode:'tozero',title:{text:'Tokens / week'}},xaxis:{range:windowRange(x,26),title:{text:'Week starting · last 26 weeks'}},margin:{l:62,r:12,t:12,b:48}});
  const groups=[['Open weights',D.openrouter.open,'#8abfb0'],['Closed weights',D.openrouter.closed,'#8096b5'],['Unknown',tot.map((t,i)=>t-D.openrouter.open[i]-D.openrouter.closed[i]),'#59616d']];
  plotSafe('desk-weights',groups.map(([name,vals,color])=>({x,y:vals.map((v,i)=>T.ratio(v,tot[i])),name,stackgroup:'a',mode:'lines',line:{width:.6,color},fillcolor:color,hovertemplate:'%{y:.1%}<extra>'+name+'</extra>'})),{xaxis:{range:windowRange(x,26)},yaxis:{range:[0,1],tickformat:'.0%',title:{text:'Share of all tokens'}},showlegend:true,legend:{orientation:'h',y:-.2},margin:{l:60,r:12,t:12,b:45}});
 }else for(const id of ['desk-volume','desk-weights'])document.getElementById(id).innerHTML=empty('No complete OpenRouter week','The other sources remain independently readable.');
 function movers(){let rows=o?(deskGroup==='model'?o.models.map(m=>({...m,name:m.model})):Object.entries(D.openrouter.labs).map(([name,v])=>({name,lab:name,tokens:v[o.n],share:T.ratio(v[o.n],o.now),delta:T.change(T.ratio(v[o.n],o.now),T.ratio(v[o.j],o.before)),v}))):[];
  rows=rows.map(r=>({...r,magnitude:Math.abs(r.delta??0)})).filter(r=>(r.name+' '+r.lab).toLowerCase().includes(deskQuery.toLowerCase())&&T.finite(r.delta)).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,12);
  if(!rows.length){document.getElementById('desk-movers').innerHTML=empty('No comparable rows','Try another filter or a shorter comparison period.');return}
  table(document.getElementById('desk-movers'),[{k:'name',h:deskGroup==='model'?'Model':'Lab',f:(v,r)=>`<span class="model-name" title="${esc(v)}">${esc(compactName(v))}</span><small class="row-sub">${esc(r.lab)}</small>`},{k:'tokens',h:'Tokens / week',n:1,f:fT},{k:'share',h:'Token share',n:1,f:fP},{k:'delta',h:'Change vs '+lag+'w ago',n:1,f:fPP,cls:signed},{k:'v',h:'13 weeks',f:v=>spark(v.slice(-13))}],rows,'magnitude')}
 bindSeg('desk-group',v=>{deskGroup=v;movers()});document.getElementById('desk-query').oninput=e=>{deskQuery=e.target.value;movers()};movers();
 const launches=o?o.models.filter(m=>m.rel&&m.rel<=o.end&&m.rel>=T.add(o.end,-56)&&m.tokens>0).sort((a,b)=>b.rel.localeCompare(a.rel)).slice(0,7):[];
 document.getElementById('desk-launches').innerHTML=launches.length?`<div class="tw"><table><thead><tr><th>Recent listing</th><th class="n">Token share</th><th class="n">Share change · ${lag} weeks<br>model / parent lab</th></tr></thead><tbody>${launches.map(m=>{const l=b.rows.find(r=>r.lab===m.lab);return `<tr><td><span class="model-name" title="${esc(m.model)}">${esc(compactName(m.model))}</span><small class="row-sub">${esc(m.rel)} · ${esc(m.lab)}</small></td><td class="n">${fP(m.share)}</td><td class="n"><b class="${signed(m.delta)}">${fPP(m.delta)}</b><small class="row-sub ${signed(l?.or.delta)}">lab ${fPP(l?.or.delta)}</small></td></tr>`}).join('')}</tbody></table></div>`:empty('No recent listings with observed usage','Uses catalog listings in the last eight weeks.');
 function pricePlot(key){const rows=priced.filter(r=>r[key]>0),fr=T.envelope(rows,key);plotSafe('desk-frontier',[...['closed','open'].map(w=>{const rs=rows.filter(r=>w==='open'?r.open===true:r.open!==true);return{x:rs.map(r=>r.idx),y:rs.map(r=>r[key]),text:rs.map(r=>r.name),name:w==='open'?'Open weights':'Closed / unclassified',mode:'markers',marker:{color:w==='open'?'#8abfb0':'#8096b5',size:7,symbol:w==='open'?'circle-open':'circle'},hovertemplate:'%{text}<br>AA %{x} · $%{y:.3f} / 1M<extra></extra>'}}),{x:fr.map(r=>r.idx),y:fr.map(r=>r[key]),mode:'lines',name:'Lowest price at this score or higher',line:{color:'#dac09a',width:1,dash:'dot'},hoverinfo:'skip'}],{xaxis:{title:{text:'Artificial Analysis score · higher is better'}},yaxis:{type:'log',tickprefix:'$',title:{text:'$ / million tokens · log scale'}},hovermode:'closest',showlegend:true,legend:{orientation:'h',y:-.35},margin:{b:85,l:64,r:15,t:10}})}
 bindSeg('desk-price',pricePlot);if(priced.length)pricePlot('pout');else document.getElementById('desk-frontier').innerHTML=empty('No benchmark-matched prices','Price history is available in the source explorer when collected.');
 table(document.getElementById('desk-cost-table'),[{k:'name',h:'Highest benchmark-scored models',f:v=>esc(v)},{k:'idx',h:'AA score',n:1},{k:'pin',h:'Input $ / million',n:1,f:f$},{k:'pout',h:'Output $ / million',n:1,f:f$}],priced.slice(0,5),'idx');
 const r=D.ramp,c=D.cloudflare;let context='';
 if(r.ok){const n=r.months.length-1,all=r.vendors.all?.[n],prv=T.at(r.months,r.vendors.all,b.rampPrev);context+=`<div class="context-item"><div class="eyebrow">ENTERPRISE / RAMP · ${r.months[n]}</div><b>${all==null?'—':all.toFixed(1)+'%'} of firms paying for AI</b><p>${fPP(T.ratio(T.change(all,prv),100))} vs prior month. Paid adoption includes subscriptions; it is not inference volume.</p>${jump('ramp','Adoption & API spend')}</div>`}
 if(c.ok){const n=c.dates.length-1,rows=Object.entries(c.services).filter(([s,v])=>v[n]!=null).sort((a,b)=>a[1][n]-b[1][n]).slice(0,4);context+=`<div class="context-item"><div class="eyebrow">CONSUMER / CLOUDFLARE · ${c.asof}</div>${rows.map(([s,v])=>`<div class="rank-line"><span>${esc(s)}</span><b>#${v[n]}</b></div>`).join('')}${jump('cloudflare','DNS popularity')}</div>`}
 const dis=D.disclosures.rows||[];context+=`<div class="context-item"><div class="eyebrow">COMPANY DISCLOSURES</div>${dis.length?dis.slice(-2).reverse().map(r=>`<p><b>${esc(r.company)} · ${r.value}${esc(r.unit)}</b><br>${esc(r.metric)} · ${esc(r.date)}</p>`).join(''):'<p>No company disclosures loaded. Global inference demand remains an evidence gap.</p>'}${dis.length?jump('disclosures','Definitions & original sources'):''}</div>`;document.getElementById('desk-context').innerHTML=context;
 const urls={openrouter:'https://openrouter.ai/rankings',vercel:'https://vercel.com/ai-gateway/leaderboard',pricing:'https://openrouter.ai/models',cloudflare:'https://radar.cloudflare.com/adoption-and-usage/ai',ramp:'https://ramp.com/data/ai-index'};
 document.getElementById('desk-coverage').innerHTML=`<div class="tw"><table class="coverage-table"><thead><tr><th>Source</th><th>Status</th><th>Observed through</th><th>Interpretation boundary / last collection</th></tr></thead><tbody>${D.sourceOrder.map(id=>{const s=D.sources[id],f=T.freshness(D,id);return `<tr><td>${jump(id,esc(s.name))}${urls[id]?` <a class="original" href="${urls[id]}" target="_blank" rel="noopener">Source ↗</a>`:''}</td><td><span class="status-label ${f.state.toLowerCase()}">${f.state}</span></td><td class="n">${f.date||'—'}</td><td class="coverage-skew">${esc(s.skew)}${s.collection_issue?`<small class="row-sub collection-issue">Collection issue · ${esc(s.last_attempt)}. Retained observations shown; see run log.</small>`:''}</td></tr>`}).join('')}</tbody></table></div>`;
};
BUILD.pricing=function(el){const p=D.pricing;if(!p.ok){el.innerHTML=head(D.sources.pricing)+empty('No pricing snapshot','No price decline can be measured.');return}
 const st={q:'',weights:'all',axis:'pout',model:p.rows.find(r=>r.idx!=null)?.model||p.rows[0]?.model};
 el.innerHTML=head(D.sources.pricing)+`<div class="scope-strip"><b>${p.n_snapshots} pricing snapshot${p.n_snapshots===1?'':'s'}</b><span>${p.n_snapshots===1?'The rate of price decline cannot be measured yet.':'Select a model to compare its actual quoted prices over time.'} Artificial Analysis benchmark as of ${esc(p.quality_asof)}.</span></div><div class="block"><div class="bh"><h2>Price against quality</h2><span class="sp"></span>${seg('pr-axis',[['pin','Input price'],['pout','Output price']],'pout')}${seg('pr-o',[['all','All weights'],['open','Open'],['closed','Closed'],['unknown','Unknown']],'all')}</div><div id="pr-plot" class="plot"></div><div class="note">Dotted line: no observed model has both a higher or equal AA score and a lower price on the selected price axis. Input and output stay separate. Zero-cost models are in the table, excluded from the logarithmic chart. Benchmark quality is not usage.</div></div><div class="block"><div class="bh"><h2>Published prices by model · dollars per million tokens</h2><span class="sp"></span><label for="pr-q">Filter</label><input class="q" id="pr-q" placeholder="Model or lab…"></div><div id="pr-table"></div></div><div class="block"><div class="bh"><h2>Same-model price history</h2><span class="sp"></span><label for="pr-model">Model</label><select id="pr-model">${p.rows.map(r=>`<option value="${esc(r.model)}" ${r.model===st.model?'selected':''}>${esc(r.name)}</option>`).join('')}</select></div><div id="pr-history"></div><div id="pr-history-chart" class="plot sm"></div><div class="note">Actual observation dates; list prices exclude negotiated discounts, routing mix and taxes. Fewer than two snapshots cannot establish a price trend.</div></div><div class="block"><div class="bh"><h2>Price changes, last two snapshots</h2></div><div id="pr-ch"></div></div>`;
 function filtered(){return p.rows.filter(r=>(r.name+' '+r.model+' '+r.lab).toLowerCase().includes(st.q)&&(st.weights==='all'||(st.weights==='unknown'?r.open==null:st.weights==='open'?r.open===true:r.open===false)))}
 function render(){const rows=filtered(),pts=rows.filter(r=>r.idx!=null&&r[st.axis]>0),fr=T.envelope(pts,st.axis);plotSafe('pr-plot',[...([...new Set(pts.map(r=>r.lab))].map(l=>{const rs=pts.filter(r=>r.lab===l);return{x:rs.map(r=>r.idx),y:rs.map(r=>r[st.axis]),text:rs.map(r=>r.name),name:l,mode:'markers',marker:{color:col(l),size:9},hovertemplate:'%{text}<br>AA %{x} · $%{y:.3f}/1M<extra></extra>'}})),{x:fr.map(r=>r.idx),y:fr.map(r=>r[st.axis]),mode:'lines',line:{color:'#dac09a',dash:'dot'},hoverinfo:'skip'}],{hovermode:'closest',xaxis:{title:{text:'Artificial Analysis score · higher is better'}},yaxis:{type:'log',tickprefix:'$',title:{text:'$ / million tokens · log scale'}}});
 table(document.getElementById('pr-table'),[{k:'model',h:'Model'},{k:'lab',h:'Lab',f:labChip},{k:'open',h:'Weights',f:v=>v==null?'unknown':v?'open':'closed'},{k:'idx',h:'AA score',n:1,f:v=>v??'—'},{k:'coding',h:'Coding',n:1,f:v=>v??'—'},{k:'agentic',h:'Agentic',n:1,f:v=>v??'—'},{k:'pin',h:'Input $ / million',n:1,f:f$},{k:'pout',h:'Output $ / million',n:1,f:f$},{k:'pcache',h:'Cached input $ / million',n:1,f:f$},{k:'created',h:'Listed'}],rows,'idx')}
 function history(){const rows=p.history[st.model]||[],first=rows[0],last=rows.at(-1);document.getElementById('pr-history').innerHTML=`<div class="inline-stats"><span>${rows.length} observations</span><span>${first?.date||'—'} → ${last?.date||'—'}</span><span>Input-price change <b>${rows.length>1?fS(T.growth(last.pin,first.pin)):'—'}</b></span><span>Output-price change <b>${rows.length>1?fS(T.growth(last.pout,first.pout)):'—'}</b></span></div>`;plotSafe('pr-history-chart',['pin','pout'].map((k,i)=>({x:rows.map(r=>r.date),y:rows.map(r=>r[k]),name:i?'Output':'Input',mode:'lines+markers',line:{shape:'hv',color:i?'#dac09a':'#8abfb0'},hovertemplate:'$%{y:.3f}/1M<extra>%{fullData.name}</extra>'})),{showlegend:true,yaxis:{tickprefix:'$',rangemode:'tozero',title:{text:'$ / million tokens'}}})}
 bindSeg('pr-axis',v=>{st.axis=v;render()});bindSeg('pr-o',v=>{st.weights=v;render()});document.getElementById('pr-q').oninput=e=>{st.q=e.target.value.toLowerCase();render()};document.getElementById('pr-model').onchange=e=>{st.model=e.target.value;history()};
 if(p.changes.length)table(document.getElementById('pr-ch'),[{k:'model',h:'Model'},{k:'old_date',h:'Previous date'},{k:'new_date',h:'Current date'},{k:'in_old',h:'Input was',n:1,f:f$},{k:'in_new',h:'Input now',n:1,f:f$},{k:'out_old',h:'Output was',n:1,f:f$},{k:'out_new',h:'Output now',n:1,f:f$}],p.changes,'model',false);else document.getElementById('pr-ch').innerHTML=empty(p.n_snapshots>1?'No quoted input/output changes':'Comparison not available',p.n_snapshots>1?'Among the same models present in both snapshots.':'A second price observation is required.');render();history();
};
